### PR TITLE
Add support for Validation, Serialization and methods option. 

### PR DESCRIPTION
**Pull request by EmilianoBruni**

### CODE REVIEW

**Comment by EmilianoBruni** [comment]
Current no documentation. I hope to write something in the next days. Current works fine in swagger too.

**Comment by jeka-kiselyov** [comment]
This is massive! :slightly_smiling_face: 

Will try everything.

**Comment by EmilianoBruni** [comment]
Add documentation

**Comment by jeka-kiselyov** [comment]
This is massive, @EmilianoBruni   Thanks for contribution.

Got failed tests ( different error messages on validation, I believe it's because of different fastify version ). Works ok, but will adjust tests tomorrow and publish it on npm.

**Comment by jeka-kiselyov** [comment]
@EmilianoBruni 

it may be a simple: "Cast to date failed"
or something like:
"Author validation failed: birthday: Cast to Date failed for value \"1969-30-06\" at path \"birthday\""

Added a regex insted of string to tests, passing now:
https://github.com/jeka-kiselyov/fastify-mongoose-api/blob/master/test/validation_schemas.test.js#L226

Published on npm as 1.2.19  

Thank you!

**Pull request merged**
